In [18]:
# Bài 1
nums = [1, 2, 3, 2, 5, 1, 7, 9, 9, 4]

print("Mảng ở vị trí chẵn:", nums[::2])
print("Chuyển sang tuple:", tuple(nums))
print("Chuyển sang set:", set(nums))
print("Số phần tử bị loại trùng:", len(nums) - len(set(nums)))

Mảng ở vị trí chẵn: [1, 3, 5, 7, 9]
Chuyển sang tuple: (1, 2, 3, 2, 5, 1, 7, 9, 9, 4)
Chuyển sang set: {1, 2, 3, 4, 5, 7, 9}
Số phần tử bị loại trùng: 3


In [6]:
# Bài 2
import json

with open('data.txt', 'w', encoding='utf-8') as f:
    f.write("Dòng thứ nhất\n")
    f.write("Dòng thứ hai\n")
    f.write("Dòng thứ ba\n")
    f.write("Dòng thứ tư\n")
    f.write("Dòng thứ năm\n")

with open('data.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()
    for i, line in enumerate(lines, 1):
        print(f"Dòng {i}: {line.strip()}")

student = {"name": "An", "age": 20, "scores": [8, 9, 7]}

with open('student.json', 'w', encoding='utf-8') as f:
    json.dump(student, f)

with open('student.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
    print("JSON đọc từ file:", data)


Dòng 1: Dòng thứ nhất
Dòng 2: Dòng thứ hai
Dòng 3: Dòng thứ ba
Dòng 4: Dòng thứ tư
Dòng 5: Dòng thứ năm
JSON đọc từ file: {'name': 'An', 'age': 20, 'scores': [8, 9, 7]}


In [1]:
# Bài 3
import numpy as np

matrix = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8,9,10,11]])

print("Hàng 2:", matrix[1])
print("Cột 3:", matrix[:, 2])
print("Sub matrix", matrix[0:2, 1:3])
print("Dtype mới:", matrix.astype(float).dtype)

Hàng 2: [4 5 6 7]
Cột 3: [ 2  6 10]
Sub matrix [[1 2]
 [5 6]]
Dtype mới: float64


In [11]:
# Bài 4
import pandas as pd

name = ['An','Bình','Châu','Dũng','Hà']
age = [20,21,22,20,23]
score = [7.5, 8.0, 6.5, 9.0, 8.5]
df = pd.DataFrame({'name': name, 'age': age, 'score': score})

print(df.info)
print(df.describe())
print("\nSinh viên có điểm trên 8.0:\n", df[df['score'] > 8.0])

<bound method DataFrame.info of    name  age  score
0    An   20    7.5
1  Bình   21    8.0
2  Châu   22    6.5
3  Dũng   20    9.0
4    Hà   23    8.5>
            age     score
count   5.00000  5.000000
mean   21.20000  7.900000
std     1.30384  0.961769
min    20.00000  6.500000
25%    20.00000  7.500000
50%    21.00000  8.000000
75%    22.00000  8.500000
max    23.00000  9.000000

Sinh viên có điểm trên 8.0:
    name  age  score
3  Dũng   20    9.0
4    Hà   23    8.5


In [16]:
# Bài 5
import pandas as pd

df_students = pd.read_csv('students.csv')
df_scores = pd.read_csv('scores.csv')

merged = pd.merge(df_students, df_scores, on='id')

report = merged.groupby(['id', 'name'])['score'].agg(['min', 'max', 'mean']).reset_index()

report.to_csv('report.csv', index=False)

print(report)

   id  name  min  max  mean
0   1    An    8    9   8.5
1   2  Bình    7    7   7.0
2   3  Châu    6   10   8.0


In [21]:
# Bài 6
import numpy as np

a = np.array([[1],[2],[3],[4]])
b = np.array([[10,20,30,40,50]])

c = a * b
print("a*b =")
print(c)

print("\nsqrt =")
print(np.sqrt(c))

print("\nlog =")
print(np.log(c))

print("\nmin theo axis=1 =", np.min(c, axis=1))
print("max theo axis=1 =", np.max(c, axis=1))
print("mean theo axis=1 =", np.mean(c, axis=1))
print("std theo axis=1 =", np.std(c, axis=1))

a*b =
[[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]]

sqrt =
[[ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781]
 [ 4.47213595  6.32455532  7.74596669  8.94427191 10.        ]
 [ 5.47722558  7.74596669  9.48683298 10.95445115 12.24744871]
 [ 6.32455532  8.94427191 10.95445115 12.64911064 14.14213562]]

log =
[[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
 [2.99573227 3.68887945 4.09434456 4.38202663 4.60517019]
 [3.40119738 4.09434456 4.49980967 4.78749174 5.01063529]
 [3.68887945 4.38202663 4.78749174 5.07517382 5.29831737]]

min theo axis=1 = [10 20 30 40]
max theo axis=1 = [ 50 100 150 200]
mean theo axis=1 = [ 30.  60.  90. 120.]
std theo axis=1 = [14.14213562 28.28427125 42.42640687 56.56854249]


In [22]:
# Bài 7
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "name": ["An", "Bình", "Châu", "Dũng"],
    "age": [20, np.nan, 22, 21],
    "score": [8.5, np.nan, 7.0, 9.0],
    "city": ["Hà Nội", "HCM", np.nan, "Hà Nội"]
})

df["age"] = df["age"].fillna(df["age"].mean())
df["score"] = df["score"].fillna(df["score"].median())
df["city"] = df["city"].fillna("Unknown")
df["city"] = df["city"].astype("category")

def score_level(x):
    if x >= 8: return "Good"
    elif x >= 7: return "Average"
    return "Bad"

df["score_level"] = df["score"].apply(score_level)

age_mean = df["age"].mean()
age_std = df["age"].std()
df["age_normalized"] = (df["age"] - age_mean) / age_std
df


name   age  score     city score_level  age_normalized
0    An  20.0    8.5   Hà Nội        Good       -1.224745
1  Bình  21.0    8.5      HCM        Good        0.000000
2  Châu  22.0    7.0  Unknown     Average        1.224745
3  Dũng  21.0    9.0   Hà Nội        Good        0.000000

In [23]:
# Bài 8
import pandas as pd
from pathlib import Path
import json
from datetime import datetime

log_dir = Path("logs/")
data = []

for file_path in log_dir.glob("*.json"):
    date_str = file_path.stem.split("_")[1]
    date = datetime.strptime(date_str, "%Y-%m-%d").date()
    
    # Đọc nội dung JSON
    with open(file_path, "r", encoding="utf-8") as f:
        log_entry = json.load(f)
        log_entry["date"] = date 
        data.append(log_entry)

df = pd.DataFrame(data)

daily_report = df.groupby("date")["duration"].sum().reset_index()

daily_report.to_csv("daily_report.csv", index=False)

print("Đã xuất báo cáo daily_report.csv thành công!")


Đã xuất báo cáo daily_report.csv thành công!
