In [2]:
# Bt1
import numpy as np

arr1 = np.arange(1, 11)
print("Mảng 1 chiều:", arr1)

print("Shape:", arr1.shape)
print("Dtype:", arr1.dtype)

arr1_float = arr1.astype(float)
print("Mảng float:", arr1_float)
print("Dtype mới:", arr1_float.dtype)


arr2 = np.arange(1, 10).reshape(3, 3)
print("\nMảng 2 chiều:")
print(arr2)

print("Shape:", arr2.shape)
print("Dtype:", arr2.dtype)

arr2_float = arr2.astype(float)
print("Mảng 2D float:")
print(arr2_float)
print("Dtype mới:", arr2_float.dtype)

 

Mảng 1 chiều: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Dtype: int64
Mảng float: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Dtype mới: float64

Mảng 2 chiều:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dtype: int64
Mảng 2D float:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Dtype mới: float64


In [ ]:
# Bài 2
import numpy as np

arr1 = np.arange(1, 11)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 

print(f"first_elem: {arr1[0]}")
print(f"last_elem: {arr1[-1]}")
print(f"middle_elem: {arr1[(len(arr1) - 1)//2]}")

print(f"sliced_arr: {arr2.flatten()[2:5]}")
print(f"row2: {arr2[2, :]}")
print(f"col3: {arr2[:, 2]}")

In [ ]:
# Bài 3
import numpy as np

arr = np.array([[88, 35, 62], [11, 98, 34], [64, 24, 48]])

print(f"min: {arr.min()}")
print(f"max: {arr.max()}")
print(f"mean: {arr.mean()}")
print(f"sum: {arr.sum()}")
print(f"std: {arr.std()}")

print(f"sum of column: {arr.sum(axis=0)}")
print(f"mean of column: {arr.mean(axis=0)}")

print(f"sum of row: {arr.sum(axis=1)}")
print(f"mean of row: {arr.mean(axis=1)}")

In [ ]:
# Bài 4
import numpy as np

arr1 = np.array([[5,6,8], [7,2,4], [1,6,3]])
arr2 = np.array([10,20,30])

print(f"A + B: {arr1 + arr2}")
print(f"A + B: {arr1 - arr2}")

In [ ]:
# Bài 5
import numpy as np
import time

arr = np.random.randint(1, 21, 10)
squared = np.multiply(arr, arr)
root = np.sqrt(arr)

added = np.add(arr, 5)
multiplied = np.multiply(arr, 3)
root_ufunc = np.sqrt(arr)

arr2d = np.random.randint(1, 100, (1000, 1000))

start_vec = time.time()
vec_result = arr2d * 2 + 3
end_vec = time.time()

start_loop = time.time()
loop_result = np.zeros_like(arr2d)
for i in range(arr2d.shape[0]):
    for j in range(arr2d.shape[1]):
        loop_result[i, j] = arr2d[i, j] * 2 + 3
end_loop = time.time()

print("1D Array:", arr)
print("squared:", squared)
print("squareRoot:", root)
print("add:", added)
print("multiply:", multiplied)
print("sqrtUfunc:", root_ufunc)
print("vectorized time:", end_vec - start_vec)
print("loop time:", end_loop - start_loop)

In [ ]:
# Bài 6
import numpy as np

arr = np.array([[3, 7, 4, 5],[3, 5, 2, 4],[6, 3, 9, 7],[4, 8, 3, 5]])

print(f"sum of column: {arr.sum(axis=0)}")
print(f"moan of column: {arr.mean(axis=0)}")
print(f"std of column: {arr.std(axis=0)}")

print(f"sum of row: {arr.sum(axis=1)}")
print(f"moan of row: {arr.mean(axis=1)}")
print(f"std of row: {arr.std(axis=1)}")

In [ ]:
# Bài 7
import numpy as np
from datetime import datetime

start = datetime.now()
arr1 = np.array([[ 8, 12, 14,  6,  4],[18, 13,  2,  2, 12],[ 6, 18,  5, 10, 10],[ 9,  2,  4, 12, 12],[ 2,  3,  2, 17,  3]])
arr2 = np.array([10, 20, 30, 40, 50])

print(f"total: {arr1 + arr2}")
print(f"diff: {arr1 - arr2}")
print(f"root: {arr1**(1/2)}")
print(f"sum 5: {arr1 + 5}")

end = datetime.now()
print(f"Time to done: {end - start}")

In [ ]:
# Bài 8
import numpy as np


maxtrix = np.array([[6,9,7],[2,1,5],[7,8,3]])

if np.linalg.det(maxtrix) != 0:
    maxtrix_inv = np.linalg.inv(maxtrix)
    print("\nInverse matrix:\n", maxtrix_inv)
else:
    print("Matrix is not invertible.")

eig_values, eig_vectors = np.linalg.eig(maxtrix)

print("\nEigenvalues:", eig_values)
print("\nEigenvectors:\n", eig_vectors)